@startuml
title Vehicle Initialization
'PnC登録時の動き

'分類子一覧
box "Repository"
    database    RCP as RCP
    database    PCP as PCP
    database    CCP as CCP
end box
participant WebhookService as WebhookService
participant CPS as CPS
participant MO as MO
participant MOContractPKI as MOContractPKI
participant CPO as CPO

Actor       User as User

box "OutCar"
database    PnCサーバ as PnCサーバ
database    SOA as SOA
database    SVIS as SVIS
participant App as App

end box
box "InCar"
    participant DCM as DCM
    participant CCU as CCU
    participant CCU as CCU
    participant CECU as CECU
    participant EVCC as EVCC
    participant 充制 as 充制
    participant シス制 as シス制
end box
participant EVSE as EVSE


'車両のCSRを受け取ったところから
PnCサーバ -> PnCサーバ : OEMRoot、CA1,CA2証明書取得
PnCサーバ -> RCP       : V2GRootCertをRCPへ要求
RCP --> PnCサーバ       :V2GRootCert応答
== CSR要求(PCID取得)シーケンス ==
PnCサーバ -> PnCサーバ      : OEMProvisioning証明書の作成
== 証明書インストールシーケンス ==
PnCサーバ -> PCP        : OEMProvisioning証明書のアップロード(addOEMProvCert)



@enduml